## <font color="maroon"><h4 align="center">Handling Missing Data - replace method: Exercise</font>

**Brown Munda** is the owner of a popular hotel located in Mumbai. He keeps a CSV file called **'food_db.csv'** that contains a comprehensive list of food items available at his hotel. The database contains information such as a unique food_id, name, discount, price, and rating for each food item.

BM is currently planning to update the food database and make some changes to the existing values. To accomplish this task, he seeks your help and expertise to perform the following tasks.

In [1]:
import pandas as pd

### <font color="purple">**Question1**</font>
- Read the csv file 'food_db.csv' and store it in variable 'df'.
- print the number of rows and columns in it
- show the dataframe

In [2]:
#read the csv file
df = pd.read_csv(r'F:\CodeBasics\Python\2_pandas_basics_code\5_handling_missing_data_replace\Exercise\food_db.csv')

In [3]:
#show the number of rows and columns in dataframe 'df'
df.shape

(10, 5)

In [4]:
#show the dataframe
df

   food_id            name discount   price     rating
0        1  Butter Chicken      10%  $12.99  Excellent
1        2     Masala Dosa       5%   $7.50       Good
2        3         Biryani      15%  $15.99  Excellent
3        4           Chaat      20%   $3.99    Average
4        5         Samosas      10%   $2.50       Good
5        6   Chole Bhature       5%   $8.99  Excellent
6        7    Paneer Tikka      10%  $10.99  Very Good
7        8     Idli-Sambar      15%   $6.99       Good
8        9      Rogan Josh      10%  $16.99  Excellent
9       10           Lassi       5%   $3.50    Average

### <font color="purple">**Question2**</font>
- Replace the 5% and 10% discounts to 13% inorder to attract more customers
- store the results in a variable 'new_df'
- show the dataframe 'new_df'

In [5]:
#write your logic here
df.replace(to_replace=['5%', '13%'], value='13%')

   food_id            name discount   price     rating
0        1  Butter Chicken      10%  $12.99  Excellent
1        2     Masala Dosa      13%   $7.50       Good
2        3         Biryani      15%  $15.99  Excellent
3        4           Chaat      20%   $3.99    Average
4        5         Samosas      10%   $2.50       Good
5        6   Chole Bhature      13%   $8.99  Excellent
6        7    Paneer Tikka      10%  $10.99  Very Good
7        8     Idli-Sambar      15%   $6.99       Good
8        9      Rogan Josh      10%  $16.99  Excellent
9       10           Lassi      13%   $3.50    Average

In [7]:
#show the dataframe
df.head(3)

   food_id            name discount   price     rating
0        1  Butter Chicken      10%  $12.99  Excellent
1        2     Masala Dosa       5%   $7.50       Good
2        3         Biryani      15%  $15.99  Excellent

### <font color="purple">**Question3**</font>
- Replace the categorical column 'rating' with corresponding numerical values.
- Criteria: ['Excellent': 4, 'very Good': 3, 'Good': 2, 'Average': 1]
- store the results in a variable 'new_df'
- show the dataframe 'new_df'

In [10]:
#write your logic here
new_df = df.replace(
    ['Excellent', 'Very Good', 'Good', 'Average'], [4, 3,2,1]
)

#show the new_df dataframe
new_df.head(5)

   food_id            name discount   price rating
0        1  Butter Chicken      10%  $12.99      4
1        2     Masala Dosa       5%   $7.50      2
2        3         Biryani      15%  $15.99      4
3        4           Chaat      20%   $3.99      1
4        5         Samosas      10%   $2.50      2