In [1]:
import pandas as pd

In [2]:
#another approach

#df = pd.read_csv('2_pandas_basics_code/3_read_write_to_excel/stock_data.csv', skiprows=1)

### Header =1 -> helps to understand which row should be treated as header

In [5]:
df = pd.read_csv('2_pandas_basics_code/3_read_write_to_excel/stock_data.csv', header=1) 
df.head(5)

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

### to rename the column headers we use NAMES

In [7]:
df = pd.read_csv('2_pandas_basics_code/3_read_write_to_excel/stock_data.csv', header=1, names=["stock_symbol", "eps", "revenue", "price", "people"]) 
df.head(3)

  stock_symbol    eps  revenue price      people
0        GOOGL  27.82       87   845  larry page
1          WMT   4.61      484    65        n.a.
2         MSFT     -1       85    64  bill gates

### to read only few specific rows use NROWS

In [8]:
df = pd.read_csv('2_pandas_basics_code/3_read_write_to_excel/stock_data.csv', header=1, nrows=4) 
df

  tickers            eps  revenue  price         people
0   GOOGL          27.82       87    845     larry page
1     WMT           4.61      484     65           n.a.
2    MSFT             -1       85     64     bill gates
3    RIL   not available       50   1023  mukesh ambani

### to convert any n.a. or not available values in dataset convert it using NA_VALUES

In [15]:
#using dictionary helps only to search and change in those specific cols

In [14]:
df = pd.read_csv('2_pandas_basics_code/3_read_write_to_excel/stock_data.csv', header=1, 
                 na_values={
                     'eps': ["not available"], 
                     'people': ["n.a."],
                     'price': ['n.a.'],
                     'revenue': [-1]
                 }) 
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT  -1.00     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [18]:
df = pd.read_csv('2_pandas_basics_code/3_read_write_to_excel/stock_data.csv', header=1, 
                 na_values=['not available', -1, 'n.a.']) 
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT    NaN     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [19]:
df['pe'] = df['price']/df['eps']

In [20]:
df

  tickers    eps  revenue   price         people         pe
0   GOOGL  27.82     87.0   845.0     larry page  30.373832
1     WMT   4.61    484.0    65.0            NaN  14.099783
2    MSFT    NaN     85.0    64.0     bill gates        NaN
3    RIL     NaN     50.0  1023.0  mukesh ambani        NaN
4    TATA   5.60      NaN     NaN     ratan tata        NaN

In [22]:
df.to_csv('pe.csv', index=False)

# Read XLSX file

In [25]:
#pip install openpyxl  

#INSTALL THIS OTHER WISE YOU WOULD END UP RECEIVING AN ERROR

In [27]:
df_movies = pd.read_excel('2_pandas_basics_code/3_read_write_to_excel/movies_db.xlsx', sheet_name='movies') 
df_movies.head(5)

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5

In [28]:
df_financials = pd.read_excel('2_pandas_basics_code/3_read_write_to_excel/movies_db.xlsx', sheet_name='financials') 
df_financials.head(5)

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions       $$
3       104   180.0    854.0  Millions  Dollars
4       105   250.0    670.0  Millions      USD

In [33]:
## Converting currency

def standardized_curr(curr):
    if curr == '$$' or curr == 'Dollars':
        return 'USD'
    else: 
        return curr

df_financials = pd.read_excel('2_pandas_basics_code/3_read_write_to_excel/movies_db.xlsx', sheet_name='financials', converters={
    'currency' : standardized_curr
}) 
df_financials.head(5)

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions      USD
3       104   180.0    854.0  Millions      USD
4       105   250.0    670.0  Millions      USD

In [29]:
df_actors = pd.read_excel('2_pandas_basics_code/3_read_write_to_excel/movies_db.xlsx', sheet_name='actors') 
df_actors.head(5)

   actor_id                  name  birth_year
0        50                  Yash        1986
1        51           Sanjay Dutt        1959
2        52  Benedict Cumberbatch        1976
3        53       Elizabeth Olsen        1989
4        54       Chris Hemsworth        1983

In [30]:
df_movieactor = pd.read_excel('2_pandas_basics_code/3_read_write_to_excel/movies_db.xlsx', sheet_name='movie_actor') 
df_movieactor.head(5)

   movie_id  actor_id
0       101        50
1       101        51
2       102        52
3       102        53
4       103        54

In [31]:
df_langs = pd.read_excel('2_pandas_basics_code/3_read_write_to_excel/movies_db.xlsx', sheet_name='languages') 
df_langs.head(5)

   language_id     name
0            1    Hindi
1            2   Telugu
2            3  Kannada
3            4    Tamil
4            5  English

## merge 2 dataframes using a single column and publish a dataset

In [35]:
df_merged = pd.merge(df_movies, df_financials, on='movie_id')
df_merged.head(5)

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,1.0,12.5,Billions,INR
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,200.0,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,165.0,644.8,Millions,USD
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,180.0,854.0,Millions,USD
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5,250.0,670.0,Millions,USD

In [36]:
df_merged.to_excel('df_merged.xlsx', index=False, sheet_name='movie_financials')

# Write to EXCEL

## Write two dataframes to two separate sheets in excel

In [37]:
df_stocks = pd.DataFrame({
    'tickers': ['GOOGL', 'WMT', 'MSFT'],
    'price': [845, 65, 64 ],
    'pe': [30.37, 14.26, 30.97],
    'eps': [27.82, 4.61, 2.12]
})

df_weather =  pd.DataFrame({
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'event': ['Rain', 'Sunny', 'Snow']
})

In [38]:
with pd.ExcelWriter('stocks_weather.xlsx') as writer:
    df_stocks.to_excel(writer, sheet_name="stocks")
    df_weather.to_excel(writer, sheet_name="weather")