In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(r"F:\CodeBasics\Python\2_pandas_basics_code\4_handling_missing_data_fillna_dropna_interpolate\weather_data.csv", parse_dates = ['day'])
df.head(5)

         day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-04          NaN        9.0  Sunny
2 2017-01-05         28.0        NaN   Snow
3 2017-01-06          NaN        7.0    NaN
4 2017-01-07         32.0        NaN   Rain

In [9]:
type(df.day[0])

pandas.Timestamp

In [11]:
df.set_index('day', inplace=True)

In [12]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

## FILLNA(0)

In [15]:
df_n = df.fillna(0)

In [16]:
df_n.head(4)

            temperature  windspeed  event
day
2017-01-01         32.0        6.0   Rain
2017-01-04          0.0        9.0  Sunny
2017-01-05         28.0        0.0   Snow
2017-01-06          0.0        7.0      0

## FILLNA(with mean or median)

In [22]:
df.fillna({
    'temperature' : df.temperature.mean(),
    'windspeed' : df.windspeed.mean(),
    'event' : 'No Event'    
})

            temperature  windspeed     event
day
2017-01-01        32.00       6.00      Rain
2017-01-04        33.22       9.00     Sunny
2017-01-05        28.00       8.42      Snow
2017-01-06        33.22       7.00  No Event
2017-01-07        32.00       8.42      Rain
2017-01-08        33.22       8.42     Sunny
2017-01-09        33.22       8.42  No Event
2017-01-10        34.10       8.10    Cloudy
2017-01-11        40.00      12.00     Sunny

## FILLNA using METHOD = FFILL AND BFILL

In [24]:
df.ffill()

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        7.0   Sunny
2017-01-09         32.0        7.0   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [25]:
df.bfill()

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         28.0        9.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         32.0        7.0    Rain
2017-01-07         32.0        8.1    Rain
2017-01-08         34.1        8.1   Sunny
2017-01-09         34.1        8.1  Cloudy
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

### Use of axis

In [28]:
#is not useful in this case but you see that 

df.bfill(axis='columns')

           temperature windspeed   event
day
2017-01-01        32.0       6.0    Rain
2017-01-04         9.0       9.0   Sunny
2017-01-05        28.0      Snow    Snow
2017-01-06         7.0       7.0     NaN
2017-01-07        32.0      Rain    Rain
2017-01-08       Sunny     Sunny   Sunny
2017-01-09         NaN       NaN     NaN
2017-01-10        34.1       8.1  Cloudy
2017-01-11        40.0      12.0   Sunny

In [30]:
df.ffill(limit=1)

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        NaN   Sunny
2017-01-09          NaN        NaN   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

## use of INTERPOLATE

In [33]:
df.dtypes

temperature    float64
windspeed      float64
event              str
dtype: object

In [36]:
df['temperature'].interpolate()

day
2017-01-01    32.0
2017-01-04    30.0
2017-01-05    28.0
2017-01-06    30.0
2017-01-07    32.0
2017-01-08    32.7
2017-01-09    33.4
2017-01-10    34.1
2017-01-11    40.0
Name: temperature, dtype: float64

## DROP NA

In [37]:
df.dropna()

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

### How?
#### ANY | ALL

In [38]:
df.head(5)

            temperature  windspeed  event
day
2017-01-01         32.0        6.0   Rain
2017-01-04          NaN        9.0  Sunny
2017-01-05         28.0        NaN   Snow
2017-01-06          NaN        7.0    NaN
2017-01-07         32.0        NaN   Rain

In [39]:
df.dropna(how='any') #if any of the row value is NaN then would drop it

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [40]:
df.dropna(how = 'all') #the entire row needs to have NaN value

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [41]:
df.dropna(thresh=2) #2 non NA value

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-07         32.0        NaN    Rain
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny