In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'F:\CodeBasics\Python\2_pandas_basics_code\6_group_by\weather_by_cities.csv')

In [3]:
df.head(5)

        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
4  1/1/2017    mumbai           90          5  Sunny

In [6]:
g = df.groupby('city')
g

In [8]:
g.max()

               day  temperature  windspeed  event
city
mumbai    1/4/2017           92         15  Sunny
new york  1/4/2017           36         12  Sunny
paris     1/4/2017           54         20  Sunny

In [9]:
g.min()

               day  temperature  windspeed   event
city
mumbai    1/1/2017           85          5     Fog
new york  1/1/2017           28          6    Rain
paris     1/1/2017           42          8  Cloudy

In [16]:
g[['temperature','windspeed']].mean()

          temperature  windspeed
city
mumbai          88.50       9.25
new york        32.25       8.00
paris           47.75      12.75

In [21]:
g.obj.dtypes

day              str
city             str
temperature    int64
windspeed      int64
event            str
dtype: object

In [22]:
g.get_group('mumbai')

        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

In [23]:
g.groups.keys()

dict_keys(['mumbai', 'new york', 'paris'])

In [27]:
for city, data in g:
    print("City :", city)
    print("Data :", data)

City : mumbai
Data :         day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
City : new york
Data :         day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
City : paris
Data :          day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

In [28]:
g.describe()

         temperature                                                   \
               count   mean       std   min    25%   50%    75%   max
city
mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0

         windspeed
             count   mean       std  min   25%   50%    75%   max
city
mumbai         4.0   9.25  5.057997  5.0  5.00   8.5  12.75  15.0
new york       4.0   8.00  2.708013  6.0  6.75   7.0   8.25  12.0
paris          4.0  12.75  5.251984  8.0  9.50  11.5  14.75  20.0

In [29]:
g.size()

city
mumbai      4
new york    4
paris       4
dtype: int64

In [30]:
g.count()

          day  temperature  windspeed  event
city
mumbai      4            4          4      4
new york    4            4          4      4
paris       4            4          4      4

## Custom functions

create custom functions in group by having certain criteria
e.g.: temp b/w 80-90 in group A, 60-80 in group B, etc

In [38]:
def grp (df, idx, col):
    if 80 <= df[col].loc[idx] <= 90:
        return '80-90'
    elif 60 <= df[col].loc[idx] < 80:
        return '60-79'
    else:
        return 'Others'

In [39]:
g= df.groupby(lambda idx : grp(df, idx, 'temperature'))

In [40]:
for key, data in g:
    print("Key : ", key)
    print("Data : ", data)

Key :  80-90
Data :          day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
Key :  Others
Data :           day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy